-- Tabla CLIENTES
CREATE TABLE clientes (
  cliente_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(80)  NOT NULL,
  email        VARCHAR2(120) NOT NULL,
  direccion    VARCHAR2(200),
  fecha_alta   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_clientes_email UNIQUE (email)
);

-- Tabla PEDIDOS (relacionada con CLIENTES)
CREATE TABLE pedidos (
  pedido_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id    NUMBER NOT NULL,
  fecha_pedido  DATE DEFAULT SYSDATE NOT NULL,
  modelo_kimono VARCHAR2(80) NOT NULL,
  talla         VARCHAR2(10) NOT NULL,
  color         VARCHAR2(30) NOT NULL,
  total         NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_pedidos_cliente

  
    FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id)
);

CREATE INDEX ix_pedidos_cliente_id ON pedidos(cliente_id);


--Datos de prueba

INSERT INTO clientes (nombre, email, direccion) VALUES
('Ana Pérez',   'ana.perez@mail.com',   'C/ Girona 10, Figueres');

INSERT INTO clientes (nombre, email, direccion) VALUES
('Marc Vidal',  'marc.vidal@mail.com',  'Av. Catalunya 22, Roses');

INSERT INTO clientes (nombre, email, direccion) VALUES
('Laura Costa', 'laura.costa@mail.com', 'C/ Mar 3, L''Escala');

-- Pedidos 
INSERT INTO pedidos (cliente_id, fecha_pedido, modelo_kimono, talla, color, total)
VALUES ((SELECT cliente_id FROM clientes WHERE email='ana.perez@mail.com'),
        DATE '2026-02-01', 'Sakura', 'M', 'Azul', 89.90);

INSERT INTO pedidos (cliente_id, fecha_pedido, modelo_kimono, talla, color, total)
VALUES ((SELECT cliente_id FROM clientes WHERE email='ana.perez@mail.com'),
        DATE '2026-02-03', 'Kumo', 'S', 'Negro', 74.50);

INSERT INTO pedidos (cliente_id, fecha_pedido, modelo_kimono, talla, color, total)
VALUES ((SELECT cliente_id FROM clientes WHERE email='marc.vidal@mail.com'),
        DATE '2026-01-20', 'Hana', 'L', 'Rojo', 120.00);

COMMIT;

-- Procedimiento create

CREATE OR REPLACE PROCEDURE sp_crear_cliente (
  p_nombre    IN clientes.nombre%TYPE,
  p_email     IN clientes.email%TYPE,
  p_direccion IN clientes.direccion%TYPE,
  p_cliente_id OUT clientes.cliente_id%TYPE
) AS
BEGIN
  INSERT INTO clientes (nombre, email, direccion)
  VALUES (p_nombre, p_email, p_direccion)
  RETURNING cliente_id INTO p_cliente_id;

  COMMIT;

EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20001, 'Email ya existe (violación de clave única).');
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

CREATE OR REPLACE PROCEDURE sp_crear_pedido (
  p_cliente_id    IN pedidos.cliente_id%TYPE,
  p_fecha_pedido  IN pedidos.fecha_pedido%TYPE,
  p_modelo        IN pedidos.modelo_kimono%TYPE,
  p_talla         IN pedidos.talla%TYPE,
  p_color         IN pedidos.color%TYPE,
  p_total         IN pedidos.total%TYPE,
  p_pedido_id OUT pedidos.pedido_id%TYPE
) AS
BEGIN
  INSERT INTO pedidos (cliente_id, fecha_pedido, modelo_kimono, talla, color, total)
  VALUES (p_cliente_id, NVL(p_fecha_pedido, SYSDATE), p_modelo, p_talla, p_color, p_total)
  RETURNING pedido_id INTO p_pedido_id;

  COMMIT;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20002, 'Cliente no encontrado.');
  WHEN OTHERS THEN
    -- Si el cliente_id no existe, Oracle lanzará ORA-02291 (FK). Lo dejamos caer como error.
    ROLLBACK;
    RAISE;
END;
/

-- Procedimiento read

CREATE OR REPLACE PROCEDURE sp_buscar_clientes_por_nombre (
  p_nombre IN VARCHAR2,
  p_result OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_result FOR
    SELECT cliente_id, nombre, email, direccion, fecha_alta
    FROM clientes
    WHERE UPPER(nombre) LIKE '%' || UPPER(p_nombre) || '%'
    ORDER BY nombre;
END;
/

CREATE OR REPLACE PROCEDURE sp_buscar_pedidos_por_fecha (
  p_desde  IN DATE,
  p_hasta  IN DATE,
  p_result OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_result FOR
    SELECT p.pedido_id, p.cliente_id, c.nombre, p.fecha_pedido,
           p.modelo_kimono, p.talla, p.color, p.total
    FROM pedidos p
    JOIN clientes c ON c.cliente_id = p.cliente_id
    WHERE p.fecha_pedido >= NVL(p_desde, DATE '1900-01-01')
      AND p.fecha_pedido <  NVL(p_hasta, DATE '2999-12-31') + 1
    ORDER BY p.fecha_pedido DESC;
END;
/

-- Procedimiento update

CREATE OR REPLACE PROCEDURE sp_buscar_pedidos_por_fecha (
  p_desde  IN DATE,
  p_hasta  IN DATE,
  p_result OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_result FOR
    SELECT p.pedido_id, p.cliente_id, c.nombre, p.fecha_pedido,
           p.modelo_kimono, p.talla, p.color, p.total
    FROM pedidos p
    JOIN clientes c ON c.cliente_id = p.cliente_id
    WHERE p.fecha_pedido >= NVL(p_desde, DATE '1900-01-01')
      AND p.fecha_pedido <  NVL(p_hasta, DATE '2999-12-31') + 1
    ORDER BY p.fecha_pedido DESC;
END;
/

CREATE OR REPLACE PROCEDURE sp_actualizar_total_pedido (
  p_pedido_id IN pedidos.pedido_id%TYPE,
  p_total     IN pedidos.total%TYPE
) AS
BEGIN
  UPDATE pedidos
  SET total = p_total
  WHERE pedido_id = p_pedido_id;

  IF SQL%ROWCOUNT = 0 THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20004, 'No existe el pedido_id indicado.');
  END IF;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

-- Procedimiento delete

CREATE OR REPLACE PROCEDURE sp_borrar_cliente (
  p_cliente_id IN clientes.cliente_id%TYPE
) AS
BEGIN
  -- Primero borramos pedidos del cliente (para no violar la FK)
  DELETE FROM pedidos WHERE cliente_id = p_cliente_id;

  -- Luego borramos el cliente
  DELETE FROM clientes WHERE cliente_id = p_cliente_id;

  IF SQL%ROWCOUNT = 0 THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20006, 'No existe el cliente_id indicado.');
  END IF;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

CREATE OR REPLACE PROCEDURE sp_borrar_cliente (
  p_cliente_id IN clientes.cliente_id%TYPE
) AS
BEGIN
  -- Primero borramos pedidos del cliente (para no violar la FK)
  DELETE FROM pedidos WHERE cliente_id = p_cliente_id;

  -- Luego borramos el cliente
  DELETE FROM clientes WHERE cliente_id = p_cliente_id;

  IF SQL%ROWCOUNT = 0 THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20006, 'No existe el cliente_id indicado.');
  END IF;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/


-- Prueba CRUD

SET SERVEROUTPUT ON;

DECLARE
  v_cliente_id NUMBER;
  v_pedido_id  NUMBER;
BEGIN
  sp_crear_cliente('Nuria Soler','nuria.soler@mail.com','C/ Nou 5', v_cliente_id);
  sp_crear_pedido(v_cliente_id, SYSDATE, 'Tsuru', 'M', 'Blanco', 95.00, v_pedido_id);

  DBMS_OUTPUT.PUT_LINE('Cliente='||v_cliente_id||' Pedido='||v_pedido_id);
END;
/

BEGIN
  sp_actualizar_direccion_cliente(1, 'Dirección nueva 123');
END;
/

VARIABLE rc REFCURSOR;

BEGIN
  sp_buscar_pedidos_por_fecha(DATE '2026-01-01', DATE '2026-02-05', :rc);
END;
/

PRINT rc;

BEGIN
  sp_borrar_pedido(1);
END;
/

BEGIN
  sp_borrar_cliente(2);
END;
/

